name: Run Parser Every Hour (9:00 - 23:00 MSK)

on:
  schedule:
    - cron: '0 6-20 * * *'  # 9:00 - 23:00 по МСК (UTC+3)
  workflow_dispatch:

jobs:
  run-parser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run parser
        run: python main.py

      - name: Upload JSON
        uses: actions/upload-artifact@v4
        with:
          name: events-json
          path: events.json