name: Parser Every 1 Hour 08:00 - 00:00

on:
  schedule:
    #- cron: '0 * * * *' #каждый час
    #- cron: '*/10 * * * *' #каждые 10 минут
    # - cron: '0 5-21 * * *'  # каждый час с 08:00 до 00:00 по МСК (UTC+3)
    - cron: '40 5-20 * * *'  # каждый день в 05:40–20:40 UTC (то есть 08:45–23:45 МСК)
    #- cron: '0,30 6-23 * * *'  # Каждые полчаса с 9:00 до 00:00 по МСК (UTC+3)
    #- cron: '0,15,30,45 6-21 * * *'  # каждые 15 минут с 9:00 до 00:00 по МСК, учитывая -3 от МСК
  #workflow_dispatch:

jobs:
  run-parser:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Moscow

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check if JSON exists
        run: |
          if [ ! -f events.json ]; then
            echo "Файл events.json не найден, создаём пустой..."
            echo "[]" > events.json
          fi

#      - name: Download previous events
#        uses: actions/download-artifact@v4
#        with:
#          name: events-json
#          path: .

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run parser
        run: python main.py

      - name: Upload JSON
        uses: actions/upload-artifact@v4
        with:
          name: events-json
          path: events.json

