name: Run Parser Every 15 Minute

on:
  schedule:
    - cron: '*/5 * * * *' #каждые 5 минут
    #- cron: '0,30 6-23 * * *'  # Каждые полчаса с 9:00 до 00:00 по МСК (UTC+3)
    #- cron: '0,15,30,45 6-21 * * *'  # каждые 15 минут с 9:00 до 00:00 по МСК, учитывая -3 от МСК
  workflow_dispatch:

jobs:
  run-parser:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Moscow

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run parser
        run: python main.py

      - name: Upload JSON
        uses: actions/upload-artifact@v4
        with:
          name: events-json
          path: events.json

